const item = [
{   
    id : '001',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '002',
    item_img : 'Images/cm2.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '003',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '004',
    item_img : 'Images/cm5.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '005',
    item_img : 'Images/cm2.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '006',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '007',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '008',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '009',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '010',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '011',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
{
    id : '012',
    item_img : 'Images/cm1.jpg',
    rating:{
        stars: 4.5,
        review:1400,
    },
    item_name : "DCK Cutter Machine",
    current_price : 2000,
    original_price: 3000,
    discount: 30,
},
]